#define YY_parse_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from gpp_interpreter.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 1 "gpp_interpreter.y"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define MAX_FUNCTIONS 100

//#include "lex.yy.c" // Include this if specific Flex functions or variables are used
void yyerror(const char *s);
int yylex();

extern FILE *yyin;

int gcd(int a, int b) {
    if (b == 0) {
        return a;
    } else {
        return gcd(b, a % b);
    }
}


typedef struct {
    int intval;
    int frac;
} Fraction;

typedef enum { NODE_FRACTION, NODE_ADD,NODE_MIN,NODE_MULT,NODE_DIV ,NODE_IDEN,NODE_IF,NODE_LESS} NodeType;

typedef struct ASTNode {
    NodeType type;
    union {
        Fraction fraction;
        char *c; // Identifier
        struct {
            char operator; // '+', '-', '*', '/'
            struct ASTNode *left;
            struct ASTNode *right;
        } binaryOp; // For binary operation nodes
        struct {
            int boolean;
            struct ASTNode *condition;
            struct ASTNode *thenBranch;
            struct ASTNode *elseBranch; // Can be NULL if no else branch
        } ifNode; // For if statement nodes
    } data;
} ASTNode;

typedef struct Function {
    char* name;        // Name of the function
    char* param1;      // Name of the first parameter (or NULL if not applicable)
    char* param2;      // Name of the second parameter (or NULL if not applicable)
    ASTNode* body;     // Pointer to the AST of the function body
} Function;

Function function_table[MAX_FUNCTIONS];
int function_count = 0;

void add_function(const char* name, const char* param1, const char* param2, ASTNode* body) {
    if (function_count >= MAX_FUNCTIONS) {
        fprintf(stderr, "Function table is full\n");
        return;
    }
    function_table[function_count].name = strdup(name);
    function_table[function_count].param1 = param1 ? strdup(param1) : NULL;
    function_table[function_count].param2 = param2 ? strdup(param2) : NULL;
    function_table[function_count].body = body;
    function_count++;
}


ASTNode* create_fraction_node(int value, int frac) {
    ASTNode* node = malloc(sizeof(ASTNode));
    node->type = NODE_FRACTION;
    node->data.fraction.intval	 = value;
    node->data.fraction.frac = frac;
    return node;
}

ASTNode* create_identifier_node(char * identifier) {
    ASTNode* node = malloc(sizeof(ASTNode));
    node->type = NODE_IDEN;
    node->data.c=malloc(sizeof(char)*strlen(identifier));
    strcpy( node->data.c,identifier);
    return node;
}

ASTNode* create_if_node(ASTNode* condition, ASTNode* thenBranch, ASTNode* elseBranch ,int boolean) {
    ASTNode* node = malloc(sizeof(ASTNode));
    node->type = NODE_IF;
    node->data.ifNode.condition = condition;
    node->data.ifNode.thenBranch = thenBranch;
    node->data.ifNode.elseBranch = elseBranch;
    node->data.ifNode.boolean=boolean;
    return node;
}

ASTNode* create_binary_op_node(NodeType type, ASTNode* left, ASTNode* right) {
    ASTNode* node = malloc(sizeof(ASTNode));
    node->type = type;
    node->data.binaryOp.left = left;
    node->data.binaryOp.right = right;
    return node;
}


Fraction evaluate_ast(ASTNode* node) {
	Fraction fractin={0,0};
    Fraction left_val;
    Fraction right_val ;
    Fraction conditionValue ;
    if (!node) return fractin;

    switch (node->type) {
        case NODE_FRACTION:
            return node->data.fraction;
        case NODE_ADD:
            // Evaluate based on the specific operation, e.g., '+'
             left_val= evaluate_ast(node->data.binaryOp.left);
            right_val= evaluate_ast(node->data.binaryOp.right);
            fractin.intval=left_val.intval*right_val.frac + right_val.intval*left_val.frac;
            fractin.frac=left_val.frac*right_val.frac;

                break;
        case NODE_MIN:
            // Evaluate based on the specific operation, e.g., '+'
             left_val = evaluate_ast(node->data.binaryOp.left);
             right_val = evaluate_ast(node->data.binaryOp.right);
            fractin.intval=left_val.intval*right_val.frac - right_val.intval*left_val.frac;
            fractin.frac=left_val.frac*right_val.frac;
            break;
        case NODE_MULT:
            // Evaluate based on the specific operation, e.g., '+'
             left_val = evaluate_ast(node->data.binaryOp.left);
             right_val = evaluate_ast(node->data.binaryOp.right);
            fractin.intval=left_val.intval*right_val.intval;
            fractin.frac=left_val.frac*right_val.frac;
            break;
        case NODE_DIV:
            // Evaluate based on the specific operation, e.g., '+'
             left_val = evaluate_ast(node->data.binaryOp.left);
             right_val = evaluate_ast(node->data.binaryOp.right);
             fractin.intval=left_val.intval*right_val.intval;
            fractin.frac=left_val.frac*right_val.frac;
            break;

        case NODE_IF:
            // Evaluate the condition
            if(node->data.ifNode.condition==NULL)
            {
                if(node->data.ifNode.boolean==1)
                {
                    fractin= evaluate_ast(node->data.ifNode.thenBranch);
                }

                    break;

            }
            conditionValue = evaluate_ast(node->data.ifNode.condition);
            
            // Check the condition (assuming 0 as false, non-zero as true)
            if (conditionValue.intval == 1) {
                fractin= evaluate_ast(node->data.ifNode.thenBranch);
            } else if (node->data.ifNode.elseBranch != NULL) {
                fractin= evaluate_ast(node->data.ifNode.elseBranch);
            }
            // Return a default value if the condition is false and there is no else branch
            //return (Fraction){0, 1};
            break;
        case NODE_LESS:
            left_val = evaluate_ast(node->data.binaryOp.left);
            right_val = evaluate_ast(node->data.binaryOp.right);
            int leftnumber=left_val.intval*right_val.frac;
            int rightnumber=right_val.intval*left_val.frac;
            if(leftnumber<rightnumber)
            {
                fractin.intval=1;
                fractin.frac=-1;

            }
            else
            {
               fractin.intval=0;
                fractin.frac=-1; 
            }
            return fractin;
    }
    int commonDivisor = gcd(fractin.intval, fractin.frac);
    if (commonDivisor != 0) {
        fractin.intval /= commonDivisor;
        fractin.frac /= commonDivisor;
    }
    return fractin;
}

ASTNode* copy_ast(ASTNode* node) {
    if (node == NULL) return NULL;

    // Create a new node and copy the data from the original node
    ASTNode* new_node = malloc(sizeof(ASTNode));
    *new_node = *node; // Shallow copy

    // Deep copy children for binary operation nodes
    if (node->type == NODE_ADD || node->type == NODE_MIN || node->type == NODE_MULT || node->type == NODE_DIV) {
        new_node->data.binaryOp.left = copy_ast(node->data.binaryOp.left);
        new_node->data.binaryOp.right = copy_ast(node->data.binaryOp.right);
    }

    // ... Handle copying for other node types ...

    return new_node;
}

ASTNode* substitute_arguments(ASTNode* body, const char* param1, ASTNode* arg1, const char* param2, ASTNode* arg2) {
    if (body == NULL) return NULL;

    if (body->type == NODE_IDEN) {
        if (strcmp(body->data.c, param1) == 0) {
            return copy_ast(arg1); // Substitute with first argument
        } else if (strcmp(body->data.c, param2) == 0) {
            return copy_ast(arg2); // Substitute with second argument
        }
        return copy_ast(body); // Return the identifier as-is if it's not a parameter
    }

    // For binary operation nodes, recursively substitute in left and right subtrees
    if (body->type == NODE_ADD || body->type == NODE_MIN || body->type == NODE_MULT || body->type == NODE_DIV) {
        ASTNode* left = substitute_arguments(body->data.binaryOp.left, param1, arg1, param2, arg2);
        ASTNode* right = substitute_arguments(body->data.binaryOp.right, param1, arg1, param2, arg2);
        return create_binary_op_node(body->type, left, right);
    }

    // ... Handle other node types ...

    return copy_ast(body); // Default case
}



Function* find_function_body(const char* name) {
    for (int i = 0; i < function_count; i++) {
        if (strcmp(function_table[i].name, name) == 0) {
            return &function_table[i];
        }
    }
    return NULL; // Function not found
}


#line 259 "gpp_interpreter.y"
typedef union {
    char* str;       // For string values
    struct ASTNode* node;  // For AST nodes
} yy_parse_stype;
#define YY_parse_STYPE yy_parse_stype
#ifndef YY_USE_CLASS
#define YYSTYPE yy_parse_stype
#endif

#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parse_BISON 1

#ifndef YY_parse_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parse_COMPATIBILITY 1
 #else
  #define  YY_parse_COMPATIBILITY 0
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parse_LTYPE
   #define YY_parse_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parse_STYPE 
   #define YY_parse_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parse_DEBUG
   #define  YY_parse_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parse_USE_GOTO
  #define YY_parse_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parse_USE_GOTO
 #define YY_parse_USE_GOTO 0
#endif

#ifndef YY_parse_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parse_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parse_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parse_DEBUG */
#endif


#ifndef YY_parse_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parse_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parse_LSP_NEEDED
#ifndef YY_parse_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parse_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parse_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parse_STYPE
#define YY_parse_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parse_PARSE
#define YY_parse_PARSE yyparse
#endif
#ifndef YY_parse_LEX
#define YY_parse_LEX yylex
#endif
#ifndef YY_parse_LVAL
#define YY_parse_LVAL yylval
#endif
#ifndef YY_parse_LLOC
#define YY_parse_LLOC yylloc
#endif
#ifndef YY_parse_CHAR
#define YY_parse_CHAR yychar
#endif
#ifndef YY_parse_NERRS
#define YY_parse_NERRS yynerrs
#endif
#ifndef YY_parse_DEBUG_FLAG
#define YY_parse_DEBUG_FLAG yydebug
#endif
#ifndef YY_parse_ERROR
#define YY_parse_ERROR yyerror
#endif

#ifndef YY_parse_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parse_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parse_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parse_PARSE_PARAM
  #define YY_parse_PARSE_PARAM void
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parse_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parse_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parse_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parse_PURE
#  ifndef YYPURE
#    define YYPURE YY_parse_PURE
#  endif
#endif

#ifdef YY_parse_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parse_DEBUG 
#  endif
#endif

#ifndef YY_parse_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parse_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parse_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parse_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	KW_AND	258
#define	KW_OR	259
#define	KW_NOT	260
#define	KW_EQUAL	261
#define	KW_LESS	262
#define	KW_NIL	263
#define	KW_LIST	264
#define	KW_ELSE	265
#define	KW_APPEND	266
#define	KW_CONCAT	267
#define	KW_SET	268
#define	KW_DEF	269
#define	KW_FOR	270
#define	KW_IF	271
#define	KW_EXIT	272
#define	KW_LOAD	273
#define	KW_DISP	274
#define	KW_TRUE	275
#define	KW_FALSE	276
#define	OP_PLUS	277
#define	OP_MINUS	278
#define	OP_DIV	279
#define	OP_MULT	280
#define	OP_OP	281
#define	OP_CP	282
#define	OP_COM	283
#define	IDENTIFIER	284
#define	END_OF_LINE	285
#define	VALUEF	286


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parse_CLASS
#define YY_parse_CLASS parse
#endif
#ifndef YY_parse_INHERIT
#define YY_parse_INHERIT
#endif
#ifndef YY_parse_MEMBERS
#define YY_parse_MEMBERS 
#endif
#ifndef YY_parse_LEX_BODY
#define YY_parse_LEX_BODY  
#endif
#ifndef YY_parse_ERROR_BODY
#define YY_parse_ERROR_BODY  
#endif
#ifndef YY_parse_CONSTRUCTOR_PARAM
#define YY_parse_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parse_CONSTRUCTOR_CODE
#define YY_parse_CONSTRUCTOR_CODE
#endif
#ifndef YY_parse_CONSTRUCTOR_INIT
#define YY_parse_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parse_USE_CONST_TOKEN
#define YY_parse_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parse_USE_CONST_TOKEN != 0
#ifndef YY_parse_ENUM_TOKEN
#define YY_parse_ENUM_TOKEN yy_parse_enum_token
#endif
#endif

class YY_parse_CLASS YY_parse_INHERIT
{
public: 
#if YY_parse_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int KW_AND;
static const int KW_OR;
static const int KW_NOT;
static const int KW_EQUAL;
static const int KW_LESS;
static const int KW_NIL;
static const int KW_LIST;
static const int KW_ELSE;
static const int KW_APPEND;
static const int KW_CONCAT;
static const int KW_SET;
static const int KW_DEF;
static const int KW_FOR;
static const int KW_IF;
static const int KW_EXIT;
static const int KW_LOAD;
static const int KW_DISP;
static const int KW_TRUE;
static const int KW_FALSE;
static const int OP_PLUS;
static const int OP_MINUS;
static const int OP_DIV;
static const int OP_MULT;
static const int OP_OP;
static const int OP_CP;
static const int OP_COM;
static const int IDENTIFIER;
static const int END_OF_LINE;
static const int VALUEF;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parse_ENUM_TOKEN { YY_parse_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,KW_AND=258
	,KW_OR=259
	,KW_NOT=260
	,KW_EQUAL=261
	,KW_LESS=262
	,KW_NIL=263
	,KW_LIST=264
	,KW_ELSE=265
	,KW_APPEND=266
	,KW_CONCAT=267
	,KW_SET=268
	,KW_DEF=269
	,KW_FOR=270
	,KW_IF=271
	,KW_EXIT=272
	,KW_LOAD=273
	,KW_DISP=274
	,KW_TRUE=275
	,KW_FALSE=276
	,OP_PLUS=277
	,OP_MINUS=278
	,OP_DIV=279
	,OP_MULT=280
	,OP_OP=281
	,OP_CP=282
	,OP_COM=283
	,IDENTIFIER=284
	,END_OF_LINE=285
	,VALUEF=286


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parse_PARSE (YY_parse_PARSE_PARAM);
 virtual void YY_parse_ERROR(char *msg) YY_parse_ERROR_BODY;
#ifdef YY_parse_PURE
#ifdef YY_parse_LSP_NEEDED
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL,YY_parse_LTYPE *YY_parse_LLOC) YY_parse_LEX_BODY;
#else
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL) YY_parse_LEX_BODY;
#endif
#else
 virtual int YY_parse_LEX() YY_parse_LEX_BODY;
 YY_parse_STYPE YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
 YY_parse_LTYPE YY_parse_LLOC;
#endif
 int   YY_parse_NERRS;
 int    YY_parse_CHAR;
#endif
#if YY_parse_DEBUG != 0
 int YY_parse_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM);
public:
 YY_parse_MEMBERS 
};
/* other declare folow */
#if YY_parse_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parse_CLASS::KW_AND=258;
const int YY_parse_CLASS::KW_OR=259;
const int YY_parse_CLASS::KW_NOT=260;
const int YY_parse_CLASS::KW_EQUAL=261;
const int YY_parse_CLASS::KW_LESS=262;
const int YY_parse_CLASS::KW_NIL=263;
const int YY_parse_CLASS::KW_LIST=264;
const int YY_parse_CLASS::KW_ELSE=265;
const int YY_parse_CLASS::KW_APPEND=266;
const int YY_parse_CLASS::KW_CONCAT=267;
const int YY_parse_CLASS::KW_SET=268;
const int YY_parse_CLASS::KW_DEF=269;
const int YY_parse_CLASS::KW_FOR=270;
const int YY_parse_CLASS::KW_IF=271;
const int YY_parse_CLASS::KW_EXIT=272;
const int YY_parse_CLASS::KW_LOAD=273;
const int YY_parse_CLASS::KW_DISP=274;
const int YY_parse_CLASS::KW_TRUE=275;
const int YY_parse_CLASS::KW_FALSE=276;
const int YY_parse_CLASS::OP_PLUS=277;
const int YY_parse_CLASS::OP_MINUS=278;
const int YY_parse_CLASS::OP_DIV=279;
const int YY_parse_CLASS::OP_MULT=280;
const int YY_parse_CLASS::OP_OP=281;
const int YY_parse_CLASS::OP_CP=282;
const int YY_parse_CLASS::OP_COM=283;
const int YY_parse_CLASS::IDENTIFIER=284;
const int YY_parse_CLASS::END_OF_LINE=285;
const int YY_parse_CLASS::VALUEF=286;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parse_CLASS::token */
#endif
/*apres const  */
YY_parse_CLASS::YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM) YY_parse_CONSTRUCTOR_INIT
{
#if YY_parse_DEBUG != 0
YY_parse_DEBUG_FLAG=0;
#endif
YY_parse_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		57
#define	YYFLAG		-32768
#define	YYNTBASE	32

#define YYTRANSLATE(x) ((unsigned)(x) <= 286 ? yytranslate[x] : 35)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    22,    23,    24,    25,
    26,    27,    28,    29,    30,    31
};

#if YY_parse_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     2,     4,     8,    10,    12,    18,    24,    30,    36,
    42,    49,    55,    61,    67,    72,    78,    85,    90,    96
};

static const short yyrhs[] = {    33,
     0,    34,     0,    26,    17,    27,     0,    31,     0,    29,
     0,    26,    22,    33,    33,    27,     0,    26,    23,    33,
    33,    27,     0,    26,    25,    33,    33,    27,     0,    26,
    24,    33,    33,    27,     0,    26,     7,    33,    33,    27,
     0,    26,    16,    33,    33,    33,    27,     0,    26,    16,
    33,    33,    27,     0,    26,    16,    20,    33,    27,     0,
    26,    16,    21,    33,    27,     0,    26,    29,    33,    27,
     0,    26,    29,    33,    33,    27,     0,    26,    29,    33,
    33,    33,    27,     0,    26,    14,    29,    33,     0,    26,
    14,    29,    29,    33,     0,    26,    14,    29,    29,    29,
    33,     0
};

#endif

#if (YY_parse_DEBUG != 0) || defined(YY_parse_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
   271,   296,   297,   301,   314,   315,   316,   317,   318,   319,
   320,   321,   322,   323,   324,   325,   336,   350,   352,   355
};

static const char * const yytname[] = {   "$","error","$illegal.","KW_AND","KW_OR",
"KW_NOT","KW_EQUAL","KW_LESS","KW_NIL","KW_LIST","KW_ELSE","KW_APPEND","KW_CONCAT",
"KW_SET","KW_DEF","KW_FOR","KW_IF","KW_EXIT","KW_LOAD","KW_DISP","KW_TRUE","KW_FALSE",
"OP_PLUS","OP_MINUS","OP_DIV","OP_MULT","OP_OP","OP_CP","OP_COM","IDENTIFIER",
"END_OF_LINE","VALUEF","start","exp","FUNCTION",""
};
#endif

static const short yyr1[] = {     0,
    32,    32,    32,    33,    33,    33,    33,    33,    33,    33,
    33,    33,    33,    33,    33,    33,    33,    34,    34,    34
};

static const short yyr2[] = {     0,
     1,     1,     3,     1,     1,     5,     5,     5,     5,     5,
     6,     5,     5,     5,     4,     5,     6,     4,     5,     6
};

static const short yydefact[] = {     0,
     0,     5,     4,     1,     2,     0,     0,     0,     0,     0,
     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
     3,     0,     0,     0,     0,     0,     0,     5,    18,     0,
     0,     0,     0,     0,     0,     0,    15,     0,    10,     5,
    19,    13,    14,    12,     0,     6,     7,     9,     8,    16,
     0,    20,    11,    17,     0,     0,     0
};

static const short yydefgoto[] = {    55,
     4,     5
};

static const short yypact[] = {    15,
    14,-32768,-32768,-32768,-32768,    43,   -28,    32,   -24,    43,
    43,    43,    43,    43,    26,    43,    47,    43,    43,    43,
-32768,    43,    43,    43,    43,    -2,   -18,    51,-32768,   -12,
    -4,    33,     8,    13,    18,    20,-32768,    39,-32768,    43,
-32768,-32768,-32768,-32768,    27,-32768,-32768,-32768,-32768,-32768,
    29,-32768,-32768,-32768,    57,    67,-32768
};

static const short yypgoto[] = {-32768,
    -6,-32768
};


#define	YYLAST		82


static const short yytable[] = {    16,
    17,    20,    21,    22,    23,    24,    25,    26,    39,    27,
    29,    30,    31,    32,    42,    33,    34,    35,    36,    38,
     6,    41,    43,    15,    37,    45,     2,     7,     3,     8,
     9,    51,     6,    52,    46,    10,    11,    12,    13,    47,
     1,     8,    14,     2,    48,     3,    49,    10,    11,    12,
    13,    18,    19,    53,    14,    54,    56,    15,    15,    44,
     2,     2,     3,     3,    15,    50,    57,     2,    15,     3,
     0,     2,    15,     3,     0,    28,    15,     3,     0,    40,
     0,     3
};

static const short yycheck[] = {     6,
    29,     8,    27,    10,    11,    12,    13,    14,    27,    16,
    17,    18,    19,    20,    27,    22,    23,    24,    25,    26,
     7,    28,    27,    26,    27,    32,    29,    14,    31,    16,
    17,    38,     7,    40,    27,    22,    23,    24,    25,    27,
    26,    16,    29,    29,    27,    31,    27,    22,    23,    24,
    25,    20,    21,    27,    29,    27,     0,    26,    26,    27,
    29,    29,    31,    31,    26,    27,     0,    29,    26,    31,
    -1,    29,    26,    31,    -1,    29,    26,    31,    -1,    29,
    -1,    31
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parse_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parse_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parse_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parse_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parse_CHAR = (token), YY_parse_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parse_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parse_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parse_PURE
/* UNPURE */
#define YYLEX           YY_parse_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parse_CHAR;                      /*  the lookahead symbol        */
YY_parse_STYPE      YY_parse_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parse_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parse_LSP_NEEDED
YY_parse_LTYPE YY_parse_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parse_LSP_NEEDED
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL, &YY_parse_LLOC)
#else
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parse_DEBUG != 0
int YY_parse_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parse_CLASS::
#endif
     YY_parse_PARSE(YY_parse_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parse_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parse_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parse_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parse_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parse_LTYPE *yyls = yylsa;
  YY_parse_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parse_PURE
  int YY_parse_CHAR;
  YY_parse_STYPE YY_parse_LVAL;
  int YY_parse_NERRS;
#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE YY_parse_LLOC;
#endif
#endif

  YY_parse_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parse_NERRS = 0;
  YY_parse_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parse_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parse_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parse_LSP_NEEDED
      YY_parse_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parse_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parse_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parse_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parse_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parse_LSP_NEEDED
      yyls = (YY_parse_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parse_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parse_CHAR == YYEMPTY)
    {
#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parse_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parse_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parse_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parse_CHAR);

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parse_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parse_CHAR, YY_parse_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parse_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parse_CHAR != YYEOF)
    YY_parse_CHAR = YYEMPTY;

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 1:
#line 271 "gpp_interpreter.y"
{
        Fraction result=evaluate_ast(yyvsp[0].node);
        if(result.frac==0)
        {
            yyerror("Divide By 0 is illegal!!");
            // Skip further processing of this input
            YYABORT;
        }
        else if(result.frac==-1 &&result.intval==1)
        {
            printf("True\n"); 
            return 0;
        }
        else if(result.frac==-1 &&result.intval==0)
        {
            printf("False\n"); 
            return 0;
        }
        else
        {

                printf("%df%d\n",result.intval,result.frac); 
                return 0;
        }
  ;
    break;}
case 2:
#line 296 "gpp_interpreter.y"
{ printf("#function\n"); ;
    break;}
case 3:
#line 297 "gpp_interpreter.y"
{ printf("\n"); exit(EXIT_SUCCESS); ;
    break;}
case 4:
#line 302 "gpp_interpreter.y"
{ 
        char* token = strdup(yyvsp[0].str); 
        char* intPart = strtok(token, "f"); // Split the string at 'f' to get the integer part
        char* fracPart = strtok(NULL, "f"); // Get the fractional part

        int intval = atoi(intPart); // Convert integer part to int
        int frac = atoi(fracPart); // Convert fractional part to int
        yyval.node = create_fraction_node(intval, frac);
        free(token); // Free the duplicated strin      
    ;
    break;}
case 5:
#line 314 "gpp_interpreter.y"
{ yyval.node= create_identifier_node(yyvsp[0].str); /* Handle IDENTIFIER */ ;
    break;}
case 6:
#line 315 "gpp_interpreter.y"
{  yyval.node = create_binary_op_node(NODE_ADD, yyvsp[-2].node, yyvsp[-1].node);;
    break;}
case 7:
#line 316 "gpp_interpreter.y"
{  yyval.node = create_binary_op_node(NODE_MIN, yyvsp[-2].node, yyvsp[-1].node); ;
    break;}
case 8:
#line 317 "gpp_interpreter.y"
{yyval.node = create_binary_op_node(NODE_MULT, yyvsp[-2].node, yyvsp[-1].node);;
    break;}
case 9:
#line 318 "gpp_interpreter.y"
{yyval.node = create_binary_op_node(NODE_DIV, yyvsp[-2].node, yyvsp[-1].node);;
    break;}
case 10:
#line 319 "gpp_interpreter.y"
{yyval.node = create_binary_op_node(NODE_LESS, yyvsp[-2].node, yyvsp[-1].node);;
    break;}
case 11:
#line 320 "gpp_interpreter.y"
{      yyval.node = create_if_node(yyvsp[-3].node, yyvsp[-2].node, yyvsp[-1].node,1);;
    break;}
case 12:
#line 321 "gpp_interpreter.y"
{      yyval.node = create_if_node(yyvsp[-2].node, yyvsp[-1].node, NULL,1);;
    break;}
case 13:
#line 322 "gpp_interpreter.y"
{      yyval.node = create_if_node(NULL, yyvsp[-1].node, NULL,1);;
    break;}
case 14:
#line 323 "gpp_interpreter.y"
{ yyval.node = create_if_node(NULL, NULL, NULL,0);;
    break;}
case 15:
#line 324 "gpp_interpreter.y"
{;;
    break;}
case 16:
#line 326 "gpp_interpreter.y"
{
        Function* func_body = find_function_body(yyvsp[-3].str);
          if (func_body) {
              yyval.node  = substitute_arguments(func_body->body, func_body->param1, yyvsp[-2].node, func_body->param2, yyvsp[-1].node);
              //Fraction result = evaluate_ast(substituted_body);
              //printf("Function call result: %df%d\n", result.intval, result.frac);
          } else {
              printf("Function not found: %s\n", yyvsp[-3].str);
          }
    ;
    break;}
case 17:
#line 336 "gpp_interpreter.y"
{
          Function* func_body = find_function_body(yyvsp[-4].str);
          if (func_body) {
              yyval.node  = substitute_arguments(func_body->body, func_body->param1, yyvsp[-3].node, func_body->param2, yyvsp[-2].node);
              //Fraction result = evaluate_ast(substituted_body);
              //printf("Function call result: %df%d\n", result.intval, result.frac);
          } else {
              printf("Function not found: %s\n", yyvsp[-4].str);
          }
      ;
    break;}
case 18:
#line 350 "gpp_interpreter.y"
{ //add_function($3, $4);
  ; ;
    break;}
case 19:
#line 352 "gpp_interpreter.y"
{
    //add_function($3, $4, $5); /* Function definition logic */ 
    ;
    break;}
case 20:
#line 355 "gpp_interpreter.y"
{
        add_function(yyvsp[-3].str, yyvsp[-2].str, yyvsp[-1].str, yyvsp[0].node);
      ;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parse_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parse_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parse_LLOC.first_line;
      yylsp->first_column = YY_parse_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parse_NERRS;

#ifdef YY_parse_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parse_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parse_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parse_ERROR_VERBOSE */
	YY_parse_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parse_CHAR == YYEOF)
	YYABORT;

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parse_CHAR, yytname[yychar1]);
#endif

      YY_parse_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parse_LSP_NEEDED
  yylsp--;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 360 "gpp_interpreter.y"


void yyerror(const char *s) {
    fprintf(stderr, "Syntax error!\n" );
}

int main(int argc, char* argv[]) {
    if (argc > 1) {
        yyin = fopen(argv[1], "r");
        if (yyin == NULL) {
            perror(argv[1]);
            return 1;
        }
        yyparse();
        fclose(yyin);
    } else {
        // Continuous user input
       printf("Enter commands (Ctrl+C to exit):\n");
       while (1) {
            printf("> ");
            char c;
            
            // Ensure the prompt is printed immediately
           yyparse();
           //printf("%d\n",getchar());
           //
        }
        }
    return 0;
}
